### ISSUE TITLE
WinError 5

### ISSUE THREAD

**Issue by kast0l** [niels-db/Rush-Royale-Bot#19]
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\Desktop\Rush-Royale-Bot-new-features\Src\gui.py", line 108, in start_bot
    self.update_units()
  File "C:\Users\User\Desktop\Rush-Royale-Bot-new-features\Src\gui.py", line 98, in update_units
    if not bot_handler.select_units([unit + '.png' for unit in self.selected_units]):
  File "C:\Users\User\Desktop\Rush-Royale-Bot-new-features\Src\bot_handler.py", line 44, in select_units
    [os.remove('units/' + unit) for unit in os.listdir("units")]
  File "C:\Users\User\Desktop\Rush-Royale-Bot-new-features\Src\bot_handler.py", line 44, in <listcomp>
    [os.remove('units/' + unit) for unit in os.listdir("units")]
PermissionError: [WinError 5] Отказано в доступе: 'units/unit_rank' 

What is this problem?

**Comment by Piet-Jacobs** [comment]
PermissionError: [WinError 5] Отказано в доступе: 'units/unit_rank'

There is a permission issue on your files

**Comment by kast0l** [comment]
> 

What causes this problem and how can I fix it? Now I just deleted this folder and everything works, but if there are better ways to solve this problem?

**Comment by Piet-Jacobs** [comment]
Just Windows things...
