### ISSUE TITLE
With hypervision activated in windows the bot doesn't recognize bluestacks

### ISSUE THREAD

**Issue by Gowl95** [niels-db/Rush-Royale-Bot#29]
Title

**Comment by Piet-Jacobs** [comment]
Not a bot issue, but I have the same.

Workaround is to adjust the port range in port_scan.py and set it to the port value from Bluestacks > Advanced > ADB > 127.0.0.1:PORT

**Comment by felipeangelo91** [comment]
> Not a bot issue, but I have the same.
> 
> Workaround is to adjust the port range in port_scan.py and set it to the port value from Bluestacks > Advanced > ADB > 127.0.0.1:PORT

I solved the problem following your instructions but now the bot is looping at the game home screen, bot log keeps saying 'lost' 

also, the bot is trying to exit the game because the game prompts the 'are you sure you want to exit the game?'

**Comment by ren-paz** [comment]
is this workaround still working? I changed scan_ports to only attempt to connect to 5555 which is what my bluestack adb uses, but the bot is still raising a no device found exception

```
* daemon not running; starting now at tcp:5037
* daemon started successfully
Scanning 127.0.0.1 Ports 2770 - 2900
Started 1 threads
Ports Open: []
Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "F:\Programming\Rush-Royale-Bot\Src\gui.py", line 116, in start_bot
    self.bot_instance = bot_handler.start_bot_class(self.logger)
  File "F:\Programming\Rush-Royale-Bot\Src\bot_handler.py", line 63, in start_bot_class
    bot = bot_core.Bot()
  File "F:\Programming\Rush-Royale-Bot\Src\bot_core.py", line 29, in __init__
    raise Exception("No device found!")
Exception: No device found!
```

edit: seems to be an issue with bluestacks ever since they changed it to a static port, reverting to an older version worked
