### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FaustRUS** [niels-db/Rush-Royale-Bot#5]
The bot enters the 7th floor well , but after it exposes the first 4 pawns , it gives an error !

Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\everm\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\everm\AppData\Local\Programs\Python\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\everm\OneDrive\Рабочий стол\Rush-Royale-Bot-new-features\Src\bot_handler.py", line 135, in bot_loop
    grid_df, bot.unit_series, bot.merge_series, bot.df_groups, bot.info = combat_loop(
  File "C:\Users\everm\OneDrive\Рабочий стол\Rush-Royale-Bot-new-features\Src\bot_handler.py", line 80, in combat_loop
    grid_df, unit_series, merge_series, df_groups, info = bot.try_merge(prev_grid=grid_df, merge_target=user_target)
  File "C:\Users\everm\OneDrive\Рабочий стол\Rush-Royale-Bot-new-features\Src\bot_core.py", line 351, in try_merge
    if (num_merge_target >= 6 or num_dh >= 6) and (df_groups['empty.png'] <= 1):
UnboundLocalError: local variable 'num_dh' referenced before assignment

I thought it was demon hunter , but after replacing it , nothing has changed !

**Comment by Piet-Jacobs** [comment]
Are you running scrapper without DH?
I built the scrapper logic specifically with DH in mind, but I can fix this issue later

**Comment by FaustRUS** [comment]
trapper, demon_hunter, chemist, scrapper, summoner 
Here 's the deck I 'm playing , but with any replacement , the error is the same !

**Comment by Piet-Jacobs** [comment]
Show me your config.ini please

**Comment by FaustRUS** [comment]
[bot]
floor = 7
mana_level = 1,2,3
units = trapper, demon_hunter, chemist, scrapper, summoner
dps_unit = bruser
pve = True
watch_ad = True
require_shaman = True
treasure_map_green = False
treasure_map_gold = False

**Comment by FaustRUS** [comment]
Everything worked , I didn 't see that there is a br user in dps_unit ! Thank you so much for the bot !

**Comment by Piet-Jacobs** [comment]
Np, I will leave this issue open because I still need to fix that error. It will trigger if you are running scrapper without demon_hunter as dps_unit
